### ISSUE TITLE
Workflow recommendations

### ISSUE THREAD

**Issue by faddat** [b3log/solo#12084]
Hi,

I'm going to be using Wide to work on kdaemon (github.com/superordinate/kdaemon )

Do you have any workflow recommendations for wide, or any handy "before you get started, you should....."

Thanks!
-Jake

PS:
It's fantastic to see all of this high-quality go code from China!  I think a lot has changed in Chinese Open Source even in the past year (Lived in Shanghai & Shzenzhen for ~2.5 years....)

Oh, and I wanted to ask-- is oschina still the big open source online hangout or....?  Thanks :).

**Comment by 88250** [comment]
Hi,

I think [LiteIDE](https://github.com/visualfc/liteide) is more suitable than [Wide](https://github.com/b3log/wide) if you working on local env. There are a lot of issues to enhance on Wide. 

[Here](http://hacpai.com/article/1438407961481) is the product orientation of Wide (in Chinese).

The [OSChina](http://www.oschina.net) is the biggest and the most popular open source network in China so far, it is so wonderful.

PS:

Here is [Solo](https://github.com/b3log/solo)'s repository rather than Wide's. :smirk:
