### ISSUE TITLE
文件上传至服务器

### ISSUE THREAD

**Issue by immotor-bill** [b3log/solo#12124]
不支持图片上传到本地，感觉很不好啊，建议支持

**Comment by 88250** [comment]
谢谢反馈！后续可能会考虑（如果很多人都需求的话）。

**Comment by TiSongWen** [comment]
现在solo图片上传功能的前提是配置七牛吗？

**Comment by 88250** [comment]
@TiSongWen 是的呢

**Comment by kkmgc** [comment]
建议支持

**Comment by 88250** [comment]
@kkmgc 谢谢反馈，还需要再收集一些用户反馈再决定。

**Comment by czwer** [comment]
建议支持本地上传

**Comment by 88250** [comment]
@czwer 收到，谢谢反馈。

**Comment by ZhaoYueNing** [comment]
非常建议 支持 **本地上传**的功能

**Comment by 88250** [comment]
@ZhaoYueNing 收到，谢谢反馈。

**Comment by zhuwenbing** [comment]
建议支持

**Comment by yhnnhyyhnn** [comment]
应该有很多人希望加上

**Comment by 88250** [comment]
@yhnnhyyhnn 收到，下个版本就加上 :)

**Comment by 88250** [comment]
1.8 里面暂时不加入了，设计还没有思考清楚：

* 配置默认上传保存的目录路径在什么地方比较合适
* 和七牛的配置优先级问题

这两个会加大复杂度，让大家使用时更麻烦，不如直接注册七牛来得快捷。

**Comment by yhnnhyyhnn** [comment]
知道了，谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [b3log/solo] 文件上传至服务器 (#12124)发件人：D 收件人：b3log/solo 抄送：罗凯 ,Mention 1.8 里面暂时不加入了，设计还没有思考清楚：

配置默认上传保存的目录路径在什么地方比较合适
和七牛的配置优先级问题

这两个会加大复杂度，让大家使用时更麻烦，不如直接注册七牛来得快捷。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/b3log/solo","title":"b3log/solo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/b3log/solo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@88250 in #12124: 1.8 里面暂时不加入了，设计还没有思考清楚：\r\n\r\n* 配置默认上传保存的目录路径在什么地方比较合适\r\n* 和七牛的配置优先级问题\r\n\r\n这两个会加大复杂度，让大家使用时更麻烦，不如直接注册七牛来得快捷。"}],"action":{"name":"View Issue","url":"https://github.com/b3log/solo/issues/12124#issuecomment-274303841"}}}

**Comment by pencilso** [comment]
感觉没有太大的必要上传到服务器本地，如果说万一某一天迁移服务器的话，你还得把图片和数据库打包备份下来。

**Comment by BianJian** [comment]
商业环境 肯定要有这个选项啊..

**Comment by githubzaibao** [comment]
建议支持本地存储，多一种选择总是好的

**Comment by hutuchong** [comment]
呼吁本地上传功能

**Comment by hai046** [comment]
强烈建议能上传到本地

**Comment by hai046** [comment]
我按照源码添加了一个 `UploadProcessor` ，然后把七牛的url变成了 `/upload` 并把图片保存到`images/upload`文件夹    就完成实现了保存本地
```
  @RequestProcessing(value = "/upload", method = HTTPRequestMethod.POST)
    public void upload(final HTTPRequestContext context) {
        final HttpServletRequest request = context.getRequest();

        final JSONRenderer renderer = new JSONRenderer();

        context.setRenderer(renderer);
        final JSONObject jsonObject = new JSONObject();
memoryFileUploadFactory.setMaxFileSize(MAX_SIZE);
            MultipartStreamParser multipartStreamParser = new MultipartStreamParser(
                    memoryFileUploadFactory);
            multipartStreamParser.parseRequestStream(inputStream, "UTF-8");
            String key = multipartStreamParser.getParameter("key");
 Iterator<String> iterator = multipartStreamParser.getFileParameterNames().iterator();
            while (iterator.hasNext()) {
                String name = iterator.next();
                FileUpload file = multipartStreamParser.getFile(name);
                File saveFile = new File(BASE_DIR, key);
                FileUtils.writeByteArrayToFile(saveFile, file.getFileContent());
                files.put(name);

                jsonObject.put("key", saveFile.getPath());

                logger.info("save {}", saveFile.getAbsolutePath());
                break;
            }
……

```
注：本人纯属于个人学习使用，没有用于其他用途

**Comment by lihuibo128** [comment]
团队内部使用，机器不能连接外网，所以急需能够上传图片和文件到本地功能，搭建的是2.4版本的，请教什么时候能够支持这个功能呢？急需

**Comment by 88250** [comment]
@lihuibo128 可能要让你失望了，我还是坚持初衷，不打算添加了。你参考一下楼上的实现，自己尝试改造一下吧。

**Comment by 3xmq** [comment]
建议支持本地图片存储！

**Comment by hmmzhtx** [comment]
这个我这边基本图片是放到新浪中的
无本地存储，看来得自己动手了

**Comment by jliu666** [comment]
阿里云的OSS能够使用吗？或者还是得自己动手写一个

**Comment by 88250** [comment]
@jliu666 目前只内置了七牛云的实现

**Comment by DarknessChaser** [comment]
这个博客系统是可以用来当小团伙临时避难的地方的。。。搞了七牛就又回去了。

**Comment by 88250** [comment]
@DarknessChaser Excuse me????

**Comment by zwxbest** [comment]
1G内存的vps的ssd都在20G或者25G，个人博客存个图片没压力啊。
之前用七牛被盗刷，现在还欠着费呢。

**Comment by 88250** [comment]
感谢各位， 下个版本（v2.7.0） 将进行该特性实现。

**Comment by battlesteed** [comment]
建议加个上传到本地的功能

**Comment by 88250** [comment]
v2.8.0 中进行实现，在 solo.props 中配置文件存储路径 `uploadDir`，默认为空，即不启用本地上传，如果配置了该路径则优先使用本地上传。

**Comment by DarknessChaser** [comment]
@88250 七牛云还要实名制。。。想自己找个不用实名的地方，写点给自己看的东西。

**Comment by pencilso** [comment]
为什么这个issues还在讨论....

**Comment by fuxianwu** [comment]
建议支持，哎，如果没有计划支持，就只能换了，虽然觉得这个很好用

**Comment by 88250** [comment]
@fuxianwu 已经支持了，请看文档 https://hacpai.com/article/1442418791213 末尾处。

**Comment by 88250** [comment]
v2.9.8 支持阿里云 OSS https://github.com/b3log/solo/issues/12497
